### ISSUE TITLE
Comment anchor to the same page

### ISSUE THREAD

**Issue by Jonbrowe** [satrya/comments-widget-plus#1]
Hi there, we are using your cool comments plugin here: [http://test2.savemi.net/activity/](http://test2.savemi.net/activity/).  Currently the comment links anchor to the page of the article.  Instead, we would like them to anchor to the same page - so that the user doesnt leave that page.  Is this possible?

Best Regards

Jon

**Comment by gasatrya** [comment]
Hi @Jonbrowe  I am sorry for late reply, it seems the page is not existed anymore? The comment anchor will always go to the post page, except if you click it on the same page.
